name: gunsmith_dev

services:
  postgres:
    container_name: postgres
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: gunsmith_dev
      POSTGRES_PASSWORD: gunsmith_dev
      POSTGRES_DB: gunsmith_dev
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: