spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
        default_batch_fetch_size: 100
  batch:
    job:
      enabled: false
  datasource:
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
        stringtype: unspecified
  application:
    name: gunsmith

logging:
  level:
    io.github.pgatzka.gunsmith: info
    org.hibernate.orm: warn
    org.springframework.orm.jpa.persistenceunit.SpringPersistenceUnitInfo: warn

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus